apiVersion: apps/v1
kind: Deployment
metadata:
  name: configservice
  labels:
    app: configservice
spec:
  selector:
    matchLabels:
      app: configservice
  replicas: 1
  template:
    metadata:
      labels:
        app: configservice
    spec:
      containers:
      - name: configservice
        image: aribakan/configservice:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: configservice
  labels:
    app: configservice
spec:
  selector:
    app: configservice
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP