apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaservice
  labels:
    app: eurekaservice
spec:
  selector:
    matchLabels:
      app: eurekaservice
  replicas: 1
  template:
    metadata:
      labels:
        app: eurekaservice
    spec:
      containers:
      - name: eurekaservice
        image: aribakan/eurekaservice:latest
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaservice
  labels:
    app: eurekaservice
spec:
  selector:
    app: eurekaservice
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30000 # Puedes asignar un puerto accesible
  type: NodePort