apiVersion: v1
kind: Service
metadata:
  name: mysql-simulate
  labels:
    app: mysql-simulate
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-simulate
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-simulate
  labels:
    app: mysql-simulate
spec:
  selector:
    matchLabels:
      app: mysql-simulate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-simulate
    spec:
      containers:
      - image: mysql:latest
        name: mysql-simulate
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-simulate-root-credentials
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-credentials
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-db
              key: name
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi