apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitude
  labels:
    app: solicitude
spec:
  selector:
    matchLabels:
      app: solicitude
  replicas: 1
  template:
    metadata:
      labels:
        app: solicitude
    spec:
      containers:
      - name: solicitude
        image: aribakan/solicitude:latest
        ports:
        - containerPort: 8093
        env:
        - name: SERVER_PORT
          value: "0"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: DB_HOST_SOLICITUDE
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: DB_PORT_SOLICITUDE
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: DB_NAME_SOLICITUDE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password