server:
  port: 8082
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/arinabilan/minikube_proyecto
          search-paths: configData
  application:
    name: configService
